### ISSUE TITLE
Extra bytes change values when compressed

### ISSUE THREAD

**Issue by AsgerPetersen** [LASzip/LASzip#62] opened 2019-11-09 10:19 UTC
This issue was originally discussed at PDAL/PDAL#2799, but it appears to be a laszip issue.

I have a las file with "pulse width" extra bytes having values in the range [0,2.55]. When this las file is compressed with laszip the values change and are now in a completely different range (for the decimated file [3.051757812e-05,1.53]).

```bash
$ laszip -i out_decimated.las -o out_decimated.laz
$ lasdiff -i out_decimated.las -i out_decimated.laz
checking 'out_decimated.las' against 'out_decimated.laz'
headers are identical.
17 extra_bytes of point 4 of 15999 are different: 0 72 225 122 20 174 199 41 != 0 72 225 122 20 174 199 41
17 extra_bytes of point 5 of 15999 are different: 0 82 184 30 133 235 209 34 != 0 82 184 30 133 235 209 34
17 extra_bytes of point 11 of 15999 are different: 0 10 215 163 112 61 138 42 != 0 10 215 163 112 61 138 42
17 extra_bytes of point 14 of 15999 are different: 0 92 143 194 245 40 220 39 != 0 92 143 194 245 40 220 39
17 extra_bytes of point 27 of 15999 are different: 0 215 163 112 61 10 215 32 != 0 215 163 112 61 10 215 32
already 5 points are different ... shutting up.
3107 points are different.
both have 15999 points. took 0.026597 secs.
```

This is the input file:
[out_decimated.las.zip](https://github.com/LASzip/LASzip/files/3827143/out_decimated.las.zip)
Please note that the file should only be used for debugging purposes.

### lasinfo for both files:

Input las-file:
<details>
```
$ lasinfo out_decimated.las
lasinfo (171231) report for out_decimated.las
reporting all LAS header entries:
  file signature:             'LASF'
  file source ID:             0
  global_encoding:            16
  project ID GUID data 1-4:   00000000-0000-0000-0000-000000000000
  version major.minor:        1.4
  system identifier:          'LAStools (c) by rapidlasso GmbH'
  generating software:        'las2las (version 171231)'
  file creation day/year:     247/2019
  header size:                375
  offset to point data:       1005
  number var. length records: 1
  point data format:          6
  point data record length:   47
  number of point records:    0
  number of points by return: 0 0 0 0 0
  scale factor x y z:         0.001 0.001 0.001
  offset x y z:               500000 6000000 0
  min x y z:                  727000.052 6171000.134 15.938
  max x y z:                  727999.876 6171999.842 60.628
  start of waveform data packet record: 0
  start of first extended variable length record: 0
  number of extended_variable length records: 0
  extended number of point records: 15999
  extended number of points by return: 14042 1529 360 67 1 0 0 0 0 0 0 0 0 0 0
variable length header record 1 of 1:
  reserved             0
  user ID              'LASF_Spec'
  record ID            4
  length after header  576
  description          'Extra Bytes Record'
    Extra Byte Descriptions
      data type: 1 (unsigned char), name "ClassFlags", description: "Class Flags", scale: 1 (not set), offset: 0 (not set)
      data type: 10 (double), name "Amplitude", description: "This is the ratio of the receive", scale: 1 (not set), offset: 0 (not set)
      data type: 10 (double), name "Pulse width", description: "", scale: 1 (not set), offset: 0 (not set)
reporting minimum and maximum for all LAS point record entries ...
  X           227000052  227999876
  Y           171000134  171999842
  Z               15938      60628
  intensity          46        427
  return_number       1          5
  number_of_returns   1          5
  edge_of_flight_line 0          0
  scan_direction_flag 0          0
  classification      2         18
  scan_angle_rank   -30         30
  user_data           0        255
  point_source_ID    22         24
  gps_time 270185.169332 271138.927098
  extended_return_number          1      5
  extended_number_of_returns      1      5
  extended_classification         2     18
  extended_scan_angle         -5046   5023
  extended_scanner_channel        0      0
number of first returns:        14042
number of intermediate returns: 427
number of last returns:         14000
number of single returns:       12470
overview over extended number of returns of given pulse: 12470 2377 898 245 9 0 0 0 0 0 0 0 0 0 0
histogram of classification of points:
            9560  ground (2)
               1  low vegetation (3)
            1153  medium vegetation (4)
            2142  high vegetation (5)
            2902  building (6)
               6  noise (7)
             142  keypoint (8)
              93  Reserved for ASPRS Definition (18)
```
</details>

Resulting laz-file:
<details>
```
$ lasinfo out_decimated.laz
lasinfo (171231) report for out_decimated.laz
reporting all LAS header entries:
  file signature:             'LASF'
  file source ID:             0
  global_encoding:            16
  project ID GUID data 1-4:   00000000-0000-0000-0000-000000000000
  version major.minor:        1.4
  system identifier:          'LAStools (c) by rapidlasso GmbH'
  generating software:        'las2las (version 171231)'
  file creation day/year:     247/2019
  header size:                375
  offset to point data:       1005
  number var. length records: 1
  point data format:          6
  point data record length:   47
  number of point records:    0
  number of points by return: 0 0 0 0 0
  scale factor x y z:         0.001 0.001 0.001
  offset x y z:               500000 6000000 0
  min x y z:                  727000.052 6171000.134 15.938
  max x y z:                  727999.876 6171999.842 60.628
  start of waveform data packet record: 0
  start of first extended variable length record: 0
  number of extended_variable length records: 0
  extended number of point records: 15999
  extended number of points by return: 14042 1529 360 67 1 0 0 0 0 0 0 0 0 0 0
variable length header record 1 of 1:
  reserved             0
  user ID              'LASF_Spec'
  record ID            4
  length after header  576
  description          'Extra Bytes Record'
    Extra Byte Descriptions
      data type: 1 (unsigned char), name "ClassFlags", description: "Class Flags", scale: 1 (not set), offset: 0 (not set)
      data type: 10 (double), name "Amplitude", description: "This is the ratio of the receive", scale: 1 (not set), offset: 0 (not set)
      data type: 10 (double), name "Pulse width", description: "", scale: 1 (not set), offset: 0 (not set)
LASzip compression (version 3.1r0 c3 50000): POINT14 3 BYTE14 3
reporting minimum and maximum for all LAS point record entries ...
  X           227000052  227999876
  Y           171000134  171999842
  Z               15938      60628
  intensity          46        427
  return_number       1          5
  number_of_returns   1          5
  edge_of_flight_line 0          0
  scan_direction_flag 0          0
  classification      2         18
  scan_angle_rank   -30         30
  user_data           0        255
  point_source_ID    22         24
  gps_time 270185.169332 271138.927098
  extended_return_number          1      5
  extended_number_of_returns      1      5
  extended_classification         2     18
  extended_scan_angle         -5046   5023
  extended_scanner_channel        0      0
number of first returns:        14042
number of intermediate returns: 427
number of last returns:         14000
number of single returns:       12470
overview over extended number of returns of given pulse: 12470 2377 898 245 9 0 0 0 0 0 0 0 0 0 0
histogram of classification of points:
            9560  ground (2)
               1  low vegetation (3)
            1153  medium vegetation (4)
            2142  high vegetation (5)
            2902  building (6)
               6  noise (7)
             142  keypoint (8)
              93  Reserved for ASPRS Definition (18)
```
</details>

**Comment by rapidlasso** [comment] 2019-11-09 18:55
Bug confirmed. Thanks for finding, reporting, and documenting it nicely. In the meantime I suggest you change your code to not use a double-precision floating point value [1] but a fixed-precision scaled integer representation (maybe quantized to 0.1 nanoseconds like RIEGL does it [2]).

[1] http://web.archive.org/web/20111018220017/https://lidarbb.cr.usgs.gov/index.php?showtopic=538

[2] http://www.riegl.com/uploads/tx_pxpriegldownloads/Whitepaper_LASextrabytes_implementation_in-RIEGLSoftware_2017-12-04.pdf

**Comment by rapidlasso** [comment] 2019-11-09 21:04
Bug found. Turns out it was always the last of the 17 extra bytes that got decoded wrongly:

`E:\software\LAStools\bin>lasdiff -i out_decimated.las -i out_decimated_dec.laz
checking 'out_decimated.las' against 'out_decimated_dec.laz'
headers are identical.
17 extra_bytes of point 4 of 15999 are different: 0 72 225 122 20 174 199 41 64 103 102 102 102 102 102 4 64 != 0 72 225 122 20 174 199 41 64 103 102 102 102 10
2 102 4 63
17 extra_bytes of point 5 of 15999 are different: 0 82 184 30 133 235 209 34 64 0 0 0 0 0 0 0 0 != 0 82 184 30 133 235 209 34 64 0 0 0 0 0 0 0 63
17 extra_bytes of point 11 of 15999 are different: 0 10 215 163 112 61 138 42 64 0 0 0 0 0 0 0 0 != 0 10 215 163 112 61 138 42 64 0 0 0 0 0 0 0 63
17 extra_bytes of point 14 of 15999 are different: 0 92 143 194 245 40 220 39 64 103 102 102 102 102 102 4 64 != 0 92 143 194 245 40 220 39 64 103 102 102 102 1
02 102 4 63
17 extra_bytes of point 27 of 15999 are different: 0 215 163 112 61 10 215 32 64 0 0 0 0 0 0 0 0 != 0 215 163 112 61 10 215 32 64 0 0 0 0 0 0 0 63
already 5 points are different ... shutting up.
3107 points are different.
both have 15999 points. took 0.088 secs.`

This was due to the new fancy "selective decompression" feature that is available with the new point types 6 and higher. The selective decompression bitmask only has support for the first 16 EXTRA BYTES and then was wrongly defaulting to FALSE (aka: do not decompress) for any EXTRA BYTE beyond the first 16 such that your 17th was simply not decompressed (and then messed up the double value it was part of). I have fixed this and we will make a new minor release soon. Note that all compressed content is good. This only is a bug in the decompressor.
`E:\software\LAStools\bin>lasdiff -i out_decimated.las -i out_decimated_dec.laz
checking 'out_decimated.las' against 'out_decimated_dec.laz'
headers are identical.
raw points are identical.
files are identical. both have 15999 points. took 0.089 secs.`

**Comment by rapidlasso** [comment] 2019-11-09 21:32
The changes in the decompressor can be seen already in this commit for LASzip inside of LASlib from LAStools: https://github.com/LAStools/LAStools/commit/29679f1f29e3f218e6ff075d4ee2e5793ac04aaa Changes will come to main LASzip branch soon.

**Comment by rapidlasso** [comment] 2019-11-09 23:04
The fix in the LAStools branch of LASzip works correctly across Linux and Windows on your file. Likely tomorrow the LASzip repo will be updates.

**Comment by rapidlasso** [comment] 2019-11-10 21:54
This was fixed with this commit: https://github.com/LASzip/LASzip/commit/162ec4eb6e5c9c930fe011ad9aeabe5a46033dbd New release as soon as @hobu agrees.

**Closed by rapidlasso** 2019-11-10 21:54 UTC

**Comment by AsgerPetersen** [comment] 2019-11-11 08:55
Thank you @rapidlasso !
